sonar.projectKey=herchr445_azure-devsecops-pfa
sonar.organization=herchr445
sonar.projectName=Azure DevSecOps PFA
sonar.projectVersion=1.0

# Source code location
sonar.sources=app,scripts
sonar.exclusions=**/node_modules/**,**/*.test.js,**/backup*/**

# Language
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info 
