#!/usr/bin/env python3
# ================================================================
# PFA DevSecOps Project - Secret Fetcher
# Fetches secrets from Azure Key Vault
# Creates .env file for the application
# NEVER stores secrets in code
# ================================================================

import subprocess
import json
import os
import datetime

# ──────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────

AZ_CMD = r"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd"
KEY_VAULT_NAME = "kv-rami-pfa-2026"
OUTPUT_ENV_FILE = "app.env"

SECRETS_TO_FETCH = {
    "DB_PASSWORD": "postgresql-admin-password",
    "APP_SECRET_KEY": "app-secret-key",
}

# ──────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ──────────────────────────────────────────────────────────────

def log(message):
    """Print timestamped message."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}")

def fetch_secret(vault_name, secret_name):
    """Fetch a secret from Azure Key Vault."""
    try:
        result = subprocess.run([
            AZ_CMD, "keyvault", "secret", "show",
            "--vault-name", vault_name,
            "--name", secret_name,
            "--query", "value",
            "--output", "tsv"
        ], capture_output=True, text=True, timeout=30)

        if result.returncode == 0:
            secret_value = result.stdout.strip()
            log(f"✅ Fetched secret: {secret_name}")
            return secret_value
        else:
            log(f"❌ Failed to fetch: {secret_name}")
            log(f"   Error: {result.stderr.strip()}")
            return None
    except Exception as e:
        log(f"❌ Error fetching {secret_name}: {str(e)}")
        return None

def create_env_file(secrets, output_file):
    """Create .env file with fetched secrets."""
    try:
        with open(output_file, "w") as f:
            f.write(f"# Auto-generated by fetch_secrets.py\n")
            f.write(f"# Generated at: {datetime.datetime.now()}\n")
            f.write(f"# DO NOT COMMIT THIS FILE\n\n")

            # Database configuration
            f.write("# Database Configuration\n")
            f.write(f"DB_HOST=psql-rami-pfa.postgres.database.azure.com\n")
            f.write(f"DB_PORT=5432\n")
            f.write(f"DB_NAME=pfa_app_db\n")
            f.write(f"DB_USER=psqladmin\n")
            f.write(f"DB_PASSWORD={secrets.get('DB_PASSWORD', '')}\n\n")

            # Application configuration
            f.write("# Application Configuration\n")
            f.write(f"APP_SECRET_KEY={secrets.get('APP_SECRET_KEY', '')}\n")
            f.write(f"APP_ENV=production\n")
            f.write(f"APP_PORT=3000\n")

        log(f"✅ Created {output_file} successfully")
        return True
    except Exception as e:
        log(f"❌ Failed to create {output_file}: {str(e)}")
        return False

# ──────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────

def main():
    log("=" * 60)
    log("PFA DevSecOps - Secret Fetcher")
    log(f"Key Vault: {KEY_VAULT_NAME}")
    log("=" * 60)

    # Fetch all secrets
    log("\n--- Fetching Secrets from Key Vault ---")
    secrets = {}
    for env_var, secret_name in SECRETS_TO_FETCH.items():
        value = fetch_secret(KEY_VAULT_NAME, secret_name)
        if value:
            secrets[env_var] = value

    # Create .env file
    log("\n--- Creating Environment File ---")
    if secrets:
        create_env_file(secrets, OUTPUT_ENV_FILE)
        log(f"\n✅ Secrets fetched: {len(secrets)}/{len(SECRETS_TO_FETCH)}")
        log(f"✅ Environment file created: {OUTPUT_ENV_FILE}")
        log("\n⚠️  IMPORTANT: Add app.env to .gitignore!")
    else:
        log("\n❌ No secrets fetched. Check Azure CLI authentication.")

if __name__ == "__main__":
    main()